--- #YAML:1.0
name:               MojoX-Session-Store-Libmemcached
version:            0.17
abstract:           ~
author:
    - Daniel Mascarenhas <daniel.mts@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Digest::SHA1:         0
    Memcached::libmemcached:  0.4402
    MIME::Base64:         0
    Mojolicious:          0.999931
    MojoX::Session:       0.21
    Storable:             0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
